---
abstract: "Shorten GitHub URLs using GitHub's URL shortener - git.io"
author:
  - 'James Aitken <jaitken@cpan.org>'
build_requires:
  Test::More: 0
  WWW::Shorten: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Shorten-GitHub
requires:
  Carp: 0
  Exporter: 0
  URI: 0
  WWW::Shorten::generic: 0
  base: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/LoonyPandora/WWW-Shorten-GitHub/issues
  repository: git://github.com/LoonyPandora/WWW-Shorten-GitHub.git
version: 0.1.1
